# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            sudo apt-get -y install pandoc && sudo pip3 install -e .[dev,test,alldns]

      # run tests!
      - run:
          name: run tests
          command: |
            find . -type f -name *.pyc -delete | echo
            coverage erase
            coverage run --omit="*tests*,*.virtualenvs/*,*.venv/*,*__init__*,*/usr/local/lib/python2.7/dist-packages*" -m unittest discover && bash <(curl -s https://codecov.io/bash)

      - run:
          name: run tests reports
          command: |      
            coverage report --show-missing --fail-under=85

      - run:
          name: run static analyzers
          command: |
            flake8 .
            pylint --enable=E --disable=W,R,C sewer/

      - run:
          name: run sewer cli
          command: |
            sewer --version && sewer --help

      # run make upload

      - store_artifacts:
          path: test-reports
          destination: test-reports
